### ISSUE TITLE
Scoping issue with request module

### ISSUE THREAD

**Issue by micahwierenga** [den-wdi-2/project-03#3]
Trying to use the request module and not able to get information beyond a console.log. Seems like a scoping issue and have tried everything from return the variable to using vm.variable to defining the variable outside the request and then further defining it inside request. None of these work. Guy, Larry, Merry and I tried a few other options but nothing's working.

https://www.npmjs.com/package/request

https://blog.xervo.io/node.js-tutorial-how-to-use-request-module

https://github.com/request/request

**Comment by ZebGirouard** [comment]
Yup, spot on--an issue with scope, combined with our friend async JS.  Great work troubleshooting, and now your keys are securely on the back end!
