### ISSUE TITLE
Another github issue

### ISSUE THREAD

**Issue by gliechty** [den-wdi-2/project-03#4]
I can't seem to merge a branch with the master...we tried last night several times with no luck, and same this morning. None of us knows what the issue is, and we've all double-checked my terminal commands. When I push to my remote branch and try to merge, the master says there are no changes to commit/merge. When I pull the master, it doesn't have my changes, but on my branch they're clearly there. Help??

**Comment by ZebGirouard** [comment]
Looks like merge was happening in the wrong direction.  All set now.
